package globalConfig

const (
	AUTH_METHOD_BASIC = "basic"

	AUTH_METHODS_PATH = "config/auth"

	OUTPUTH_TYPE_TOKEN = "token"

	CLAIM_VALID_FORMAT_LIST  = "list"
	CLAIM_VALID_FORMAT_VALUE = "value"

	DATASOURCE_TYPE_SERVICE    = "service"
	DATASOURCE_TYPE_CONNECTION = "connection"
	DATASOURCE_TYPE_SESSION    = "session"

	SOURCE_ENCRYPTION_ENV   = "env"
	SOURCE_ENCRYPTION_REDIS = "redis"
	SOURCE_ENCRYPTION_LOCAL = "local"
	SOURCE_ENCRIPTION_DB    = "db"

	CONNECTION_DATABASE_TYPE_SQL = "sql"

	//Using secrets keys shared between the service and the client

	ALGORITHM_ENCRYPTION_TYPE_HS256 = "HS256"
	ALGORITHM_ENCRYPTION_TYPE_HS384 = "HS384"
	ALGORITHM_ENCRYPTION_TYPE_HS512 = "HS512"

	//Hash functions

	ALGORITHM_ENCRYPTION_TYPE_SHA256 = "SHA256"
	ALGORITHM_ENCRYPTION_TYPE_SHA384 = "SHA384"
	ALGORITHM_ENCRYPTION_TYPE_SHA512 = "SHA512"

	CONFIG_SERVICE_PATH = "config/settings.xml"

	POOL_SIZE_DATABASE_CONNECTION = 10
)

var (
	CurrentAuthMethods = []string{AUTH_METHOD_BASIC}
	CurrentOutputTypes = []string{OUTPUTH_TYPE_TOKEN}
	CurrentAlgorithms  = []string{
		ALGORITHM_ENCRYPTION_TYPE_HS256,
		ALGORITHM_ENCRYPTION_TYPE_HS384,
		ALGORITHM_ENCRYPTION_TYPE_HS512,
		ALGORITHM_ENCRYPTION_TYPE_SHA256,
		ALGORITHM_ENCRYPTION_TYPE_SHA384,
		ALGORITHM_ENCRYPTION_TYPE_SHA512,
	}
	CurrentSources = []string{
		SOURCE_ENCRYPTION_ENV,
		SOURCE_ENCRYPTION_REDIS,
		SOURCE_ENCRYPTION_LOCAL,
		SOURCE_ENCRIPTION_DB,
	}
	CurrentDataSourcesType = []string{
		DATASOURCE_TYPE_SERVICE,
		DATASOURCE_TYPE_CONNECTION,
		DATASOURCE_TYPE_SESSION,
	}
	CurrentClaimValidFormats = []string{
		CLAIM_VALID_FORMAT_LIST,
		CLAIM_VALID_FORMAT_VALUE,
	}
	CurrentConnectionDatabaseType = []string{
		CONNECTION_DATABASE_TYPE_SQL,
	}
)
